# DEBUG = TRUE prints extra messages to the python console.
debug: true
max_threads: 4

tracker:
  frame_width: 1280
  frame_height: 960
  framerate: 30
  # Modes: BOX, GESTURE
  mode: GESTURE
  box:
    # Box size
    width: 640
    height: 480
    # Box position
    x: 320
    y: 420



server:
  host: 0.0.0.0
  port: 5000

database:
  path: "./db/database.db"

arduino:
  host: 172.20.10.2
  port: 5001

logs:
  directory: "./logs"
  log_to_database: True
  log_to_logger: True
  log_to_thingspeak: True

