# DEBUG = TRUE prints extra messages to the python console.
debug: false

tracker:
  max_threads: 4
  # Resolution
  frame_width: 1280
  frame_height: 960
  # Most webcams work at 30 or 60fps
  # You can further lower this value on low-end machines.
  framerate: 30
  # Modes: BOX, GESTURE
  mode: GESTURE
  box:
    # Box size
    width: 640
    height: 480
    # Box position
    x: 320
    y: 420



server:
  host: 0.0.0.0
  port: 5000

database:
  path: "./db/database.db"

arduino:
  host: 172.20.10.2
  port: 5001

# Logging Configuration.
logs:
  directory: "./logs"
  # Logs the data to a SQLite database.
  log_to_database: True
  # The Logger logs the data to a txt file.
  log_to_logger: True
  # Logs the data to ThingSpeak
  log_to_thingspeak: True

